### ISSUE TITLE
Compilation FMT error on Windows 11 VS 2022 

### ISSUE THREAD

**Issue by caiobps1** [MillhioreBT/forgottenserver-downgrade#31]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use contact.millhiorebt.com for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Followed the instructions from wiki to compile on Windows 11 VS 2022
2. Set /utf-8 in project propriety
3. Try to compile in Release x64

### Actual behaviour
![Captura de tela 2024-09-09 182557](https://github.com/user-attachments/assets/f1b21c34-bc5f-47f9-b788-0a827b72379a)

This issue can be associate to my fmt version? I am using fmt11 from the command .\vcpkg install fmt 

I've tried compile in my VM ubuntu 22.04 and everything goes right.

Thanks for help! Congratulations for your amazing project, will be very useful for mine.

**Comment by nolanggz** [comment]
simple solution...
forgot an include in script.cpp archive
upon #include <fmt/color.h>
put
#include <fmt/ranges.h>

**Comment by gesior** [comment]
> 2\. Set /utf-8 in project propriety

vcpkg does not compile some C++ libraries. Fix for all compilation errors on Windows:
https://github.com/MillhioreBT/forgottenserver-downgrade/pull/34
